name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout do código
        uses: actions/checkout@v3

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🎯 Rodar testes
        run: npm test

      - name: 🚀 Construir aplicação (se necessário)
        run: npm run build
